export const games = [
    {
        name: 'Roulette E',
        displayName: 'Soccer Roulette',
        periode: 65886,
        pcode: 'p7e',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T9_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '24D',
        displayName: '24D',
        periode: 2349802,
        pcode: 'p6',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=24D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Dice 6',
        displayName: 'Dice 6',
        periode: 3595164,
        pcode: 'm8',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=D6_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Suwit',
        displayName: 'Suwit',
        periode: 3072304,
        pcode: 'm19',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=SW_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Red White',
        displayName: 'Red White',
        periode: 3072631,
        pcode: 'm11',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=RW_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Baccarat C',
        displayName: 'Baccarat C',
        periode: 2552028,
        pcode: 'm22c',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=BCC_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=baccarat_3',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '45691-201',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '24Dspin',
        displayName: '24D Spin',
        periode: 2442812,
        pcode: 'm6',
        stream: 'https://cam2.idnstreams.com/?app=SDI&name=24DS_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '45691-201',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Baccarat',
        displayName: 'Baccarat',
        periode: 2624602,
        pcode: 'm22',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Roulette B',
        displayName: 'Roulette - Fast Table',
        periode: 1911211,
        pcode: 'p7b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=RLB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
        link: 'https://wf.idnview.com/?stream=roulette_2_360P',
    },
    {
        name: '12D',
        displayName: '12D',
        periode: 2874680,
        pcode: 'p9',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=12D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Sicbo[Dice]',
        displayName: 'Sicbo Dice',
        periode: 3178287,
        pcode: 'p12',
        stream: 'https://cam3.idnstreams.com/?app=SDI&name=SD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: '5D',
        displayName: '5D',
        periode: 1175738,
        pcode: 'm30',
        stream: 'https://cam4.idnstreams.com/?app=live&name=5D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Poker Dice',
        displayName: 'Poker Dice',
        periode: 2277989,
        pcode: 'm14',
        stream: 'https://cam3.idnstreams.com/?app=live&name=PD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Oglok',
        displayName: 'Oglok',
        periode: 3199108,
        pcode: 'm7',
        stream: 'https://cam2.idnstreams.com/?app=SDI&name=OG_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'GongBall Jitu',
        displayName: 'Gong Ball Jitu',
        periode: 1423960,
        pcode: 'm33',
        stream: 'https://cam4.idnstreams.com/?app=live&name=GB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'others',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Shio Fights',
        displayName: 'Shio Fights',
        periode: 2408611,
        pcode: 'm27',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=SF_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Billiards',
        displayName: 'Billiards',
        periode: 1127130,
        pcode: 'm13',
        stream: 'https://cam4.idnstreams.com/?app=live&name=BL_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Gong Ball',
        displayName: 'Gong Ball',
        periode: 1423960,
        pcode: 'm16',
        stream: 'https://cam4.idnstreams.com/?app=live&name=GB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Fantan',
        displayName: 'Fantan',
        periode: 1034160,
        pcode: 'm25',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=FT_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Monopoly',
        displayName: 'Monopoly',
        periode: 2065628,
        pcode: 'm20',
        stream: 'https://cam2.idnstreams.com/?app=live&name=MP_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Niuniu',
        displayName: 'Niuniu',
        periode: 897991,
        pcode: 'm24',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=NN_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'IDN 4 Stand',
        displayName: 'IDN 4 Stand',
        periode: 2533355,
        pcode: 'm28',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=IDN_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '41640-121',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Shio Balls',
        displayName: '3D Shio',
        periode: 843896,
        pcode: 'm29',
        stream: 'https://cam5.idnstreams.com/?app=live&name=3D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '41640-121',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Baccarat B',
        displayName: 'Baccarat B',
        periode: 2608681,
        pcode: 'm22b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=BCB_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=baccarat_2',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '46921-161',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Lotto',
        displayName: 'Race Ball',
        periode: 929980,
        pcode: 'm26',
        stream: 'https://cam3.idnstreams.com/?app=live&name=RC_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '46921-161',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Dragon Tiger',
        displayName: 'Dragon Tiger',
        periode: 3108953,
        pcode: 'm23',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=DT_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=dragontiger_1',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Roulette',
        displayName: 'Roulette',
        periode: 2058119,
        pcode: 'p7',
        stream: 'https://cam1.idnstreams.com/?app=SDI&name=RL_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: '48D',
        displayName: '48D',
        periode: 955300,
        pcode: 'm35',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=48D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Head Tail',
        displayName: 'Head Tail',
        periode: 3210724,
        pcode: 'm10',
        stream: 'https://cam3.idnstreams.com/?app=SDI&name=HNT_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Xoc Dia',
        displayName: 'Xoc Dia',
        periode: 1159776,
        pcode: 'm40',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=XD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Grand Prix',
        displayName: 'Grandprix Number',
        periode: 184006,
        pcode: 'm42',
        stream: 'https://cam3.idnstreams.com/?app=live&name=GP_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'balls',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Roulette D',
        displayName: 'Europe Roulette',
        periode: 985143,
        pcode: 'p7d',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T1_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T1_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Duel Dice',
        displayName: 'Duel Dice',
        periode: 1002131,
        pcode: 'm39',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=DD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Domino',
        displayName: 'Domino',
        periode: 107,
        pcode: 'm41',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T5_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T5_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Bingo Sicbo',
        displayName: 'Bingo Sicbo',
        periode: 2001533,
        pcode: 'm37',
        stream: 'https://cam3.idnstreams.com/?app=live&name=BS_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Baccarat D',
        displayName: 'Europe Baccarat',
        periode: 992024,
        pcode: 'm22d',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T2_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_uhd: '-',
        stream_4k: '-',
        stream_8k: '-',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '14542-741',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Dragon Tiger B',
        displayName: 'Dragon Tiger Wild',
        periode: 1004389,
        pcode: 'm23b',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T4_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T4_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '15389-881',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'IDN 4 Stand B',
        displayName: 'IDN 4 Stand B',
        periode: 2064086,
        pcode: 'm28b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=IDNB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Roulette C',
        displayName: 'Bingo Roulette',
        periode: 519716,
        pcode: 'p7c',
        stream: 'https://cam5.idnstreams.com/?app=live&name=BR_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '12DB',
        displayName: '12D Thunder',
        periode: 619095,
        pcode: 'p9b',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T6_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T6_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Dice 6 B',
        displayName: 'Dice 6 Fever',
        periode: 876227,
        pcode: 'm8b',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T7_1080P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
        link: 'https://ttmpools.menangtoto.pw/api/auth_toto',
    },
    {
        name: '3D',
        displayName: 'Sicbo Ball - Fast',
        periode: 2230843,
        pcode: 'm31',
        stream: 'https://cam3.idnstreams.com/?app=live&name=SB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '24D Thunder',
        periode: 9273,
        pcode: 'p6b',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T8_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'pasar',
        displayName: '6D Color',
        periode: 177084,
        pcode: 'm43',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=6D_720P',
        stream_hd: 'https://cam5.idnstreams.com/?app=SDI&name=6D_720P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'balls',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Ceme',
        periode: 8,
        pcode: 'm46',
        displayName: 'Ceme',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T5_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T5_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        new_category: ['europe', 'original', 'card game'],
        url_game: 'new_ceme_live_react/?pcode=m46',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
];
