export const games = [
    // 24D
    {
        name: '24D',
        displayName: '24D',
        periode: 2349802,
        pcode: 'p6',
        stream: '',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    // 24D Jackpot
    {
        name: '24D Thunder',
        periode: 512009,
        pcode: 'p6b',
        displayName: '24D Jackpot',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=E24D_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=E24D_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'balls',
        new_category: ['bonus game', 'europe', 'original', 'ball game'],
        url_game: 'new_24d_jp_react/?pcode=p6b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Roulette
    {
        name: 'Roulette',
        displayName: 'Roulette',
        periode: 2058119,
        pcode: 'p7',
        stream: 'https://cam1.idnstreams.com/?app=SDI&name=RL_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Roulette B',
        displayName: 'Roulette - Fast Table',
        periode: 1911211,
        pcode: 'p7b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=RLB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
        link: 'https://wf.idnview.com/?stream=roulette_2_360P',
    },
    {
        name: 'Roulette C',
        displayName: 'Bingo Roulette',
        periode: 519716,
        pcode: 'p7c',
        stream: 'https://cam5.idnstreams.com/?app=live&name=BR_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Roulette D',
        periode: 1145926,
        pcode: 'p7d',
        displayName: 'Europe Roulette',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ERL_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ERL_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe'],
        url_game: 'new_rl_react/?pcode=p7d',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Soccer Roulette',
        periode: 236941,
        pcode: 'p7e',
        displayName: 'Soccer Roulette',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=SRL_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=SRL_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['bonus game', 'europe', 'original'],
        url_game: 'new_rl_soccer/?pcode=p7e',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe Roulette 2',
        periode: 37541,
        pcode: 'p7g',
        displayName: 'Europe Roulette 2',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ERL2_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ERL2_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe'],
        url_game: 'new_rl_react/?pcode=p7g',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // 12 D
    {
        name: '12D',
        displayName: '12D',
        periode: 2874680,
        pcode: 'p9',
        stream: 'https://loader2.idnstreams.com:6443/?app=Cam&name=12D_720P&volume=0.5',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe 12D',
        periode: 1368,
        pcode: 'p9c',
        displayName: 'Europe 12D',
        stream: 'https://loader.idnstreams.com:6443/?app=Geo&name=E12D_720P&volume=0.5',
        stream_hd: 'https://loader.idnstreams.com:6443/?app=Geo&name=E12D_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe', 'fast table'],
        url_game: 'new_eu_12d_react/?pcode=p9c',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // 12 D Thunder
    {
        name: '12DB',
        periode: 790621,
        pcode: 'p9b',
        displayName: '12D Thunder',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=E12DT_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=E12DT_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        new_category: ['bonus game', 'europe', 'original', 'ball game'],
        url_game: 'new_12d_thunder_react/?pcode=p9b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Sicbo Dice
    {
        name: 'Sicbo[Dice]',
        periode: 221760,
        pcode: 'p12',
        displayName: 'Sicbo[Dice]',
        stream: 'https://cam3.idnstreams.com/?app=HDMI&name=SD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original'],
        url_game: 'new_sicbo_dice_react/?pcode=p12',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Europe Sicbo Dice',
        periode: 14800,
        pcode: 'p12b',
        displayName: 'Europe Sicbo Dice',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ESD_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ESD_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe'],
        url_game: 'new_sicbo_dice_react/?pcode=p12b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Oglok
    {
        name: 'Oglok',
        periode: 3322512,
        pcode: 'm7',
        displayName: 'Oglok',
        stream: 'https://loader2.idnstreams.com:6443/?app=Cam&name=OG_720P&volume=0.5',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original', 'dice game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    // Dice 6
    {
        name: 'Dice 6',
        displayName: 'Dice 6',
        periode: 3595164,
        pcode: 'm8',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=D6_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Dice 6 Fever
    {
        name: 'Dice 6 B',
        periode: 1083293,
        pcode: 'm8b',
        displayName: 'Dice 6 Fever',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ED6_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ED6_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['bonus game', 'europe', 'original', 'dice game'],
        url_game: 'new_dice6_fever_react/?pcode=m8b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
        link: 'https://ttmpools.menangtoto.pw/api/auth_toto',
    },
    // Red White
    {
        name: 'Red White',
        displayName: 'Red White',
        periode: 3072631,
        pcode: 'm11',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=RW_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Red White B',
        displayName: 'Europe Red White',
        periode: 3072631,
        pcode: 'm11b',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=RW_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Poker Dice
    {
        name: 'Poker Dice',
        periode: 2367455,
        pcode: 'm14',
        displayName: 'Poker Dice',
        stream: 'https://cam3.idnstreams.com/?app=HDMI&name=PD_720P',
        stream_hd: 'https://cam3.idnstreams.com/?app=HDMI&name=PD_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original', 'dice game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Poker Dice',
        periode: 51168,
        pcode: 'm14b',
        displayName: 'Europe Poker Dice',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EPD_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EPD_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe'],
        url_game: 'new_eu_poker_dice_react/?pcode=m14b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Suwit
    {
        name: 'Suwit',
        periode: 3308545,
        pcode: 'm19',
        displayName: 'Suwit',
        stream: 'https://loader2.idnstreams.com:6443/?app=Cam&name=SW_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Cam&name=SW_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original', 'dice game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe Suwit',
        periode: 11280,
        pcode: 'm19b',
        displayName: 'Europe Suwit',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ESW_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=ESW_1080PP&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe'],
        url_game: 'new_suwit_react/?pcode=m19b',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Monopoly
    {
        name: 'Monopoly',
        periode: 2175944,
        pcode: 'm20',
        displayName: 'Monopoly',
        stream: 'https://cam2.idnstreams.com/?app=live&name=MP_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original', 'dice game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Monopoly B',
        periode: 2175944,
        pcode: 'm20b',
        displayName: 'Europe Monopoly',
        stream: 'https://cam2.idnstreams.com/?app=live&name=MP_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        new_category: ['original', 'dice game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    // Baccarat
    {
        name: 'Baccarat',
        displayName: 'Baccarat',
        periode: 2624602,
        pcode: 'm22',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Baccarat B',
        displayName: 'Baccarat B',
        periode: 2608681,
        pcode: 'm22b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=BCB_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=baccarat_2',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '46921-161',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Baccarat C',
        displayName: 'Baccarat C',
        periode: 2552028,
        pcode: 'm22c',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=BCC_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=baccarat_3',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '45691-201',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Baccarat D',
        periode: 1153057,
        pcode: 'm22d',
        displayName: 'Europe Baccarat 1',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EBC_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EBC_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'card game'],
        url_game: 'new_bc_react/?pcode=m22d',
        shoePeriode: '16908-135',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe Baccarat',
        periode: 2,
        pcode: 'm22e',
        displayName: 'Europe Baccarat',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T2_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T2_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'original', 'card game', 'fast table'],
        url_game: 'new_eu_bc_react/?pcode=m22e',
        shoePeriode: '1-11',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe Baccarat 2',
        periode: 33492,
        pcode: 'm22f',
        displayName: 'Europe Baccarat 2',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EBC2_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EBC2_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['original', 'europe'],
        url_game: 'new_bc_react/?pcode=m22f',
        shoePeriode: '511-58',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Dragon Tiger
    {
        name: 'Dragon Tiger',
        displayName: 'Dragon Tiger',
        periode: 3108953,
        pcode: 'm23',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=DT_720P',
        stream_hd:
            'https://h5player.idnview.com/?muted=true&host=h5live-www1.idnview.com&stream=dragontiger_1',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Dragon Tiger Wild
    {
        name: 'Dragon Tiger B',
        periode: 1178765,
        pcode: 'm23b',
        displayName: 'Dragon Tiger Wild',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=DTW_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=DTW_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'original', 'card game'],
        url_game: 'new_dt_wild_react/?pcode=m23b',
        shoePeriode: '17904-94',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Dragon Tiger Wild 2',
        periode: 2,
        pcode: 'm23c',
        displayName: 'Dragon Tiger Wild 2',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T4_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'original', 'card game', 'fast table'],
        url_game: 'new_dt_wild_react/?pcode=m23c',
        shoePeriode: '1-11',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Europe Dragon Tiger',
        periode: 44939,
        pcode: 'm23d',
        displayName: 'Europe Dragon Tiger',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=DT2_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=DT2_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'original', 'card game', 'fast table'],
        url_game: 'new_dt_react/?pcode=m23d',
        shoePeriode: '436-82',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Fantan
    {
        name: 'Fantan',
        periode: 1113090,
        pcode: 'm25',
        displayName: 'Fantan',
        stream: 'https://loader2.idnstreams.com:6443/?app=Cam&name=FT_720P&volume=0.5',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['ball game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Fantan',
        periode: 1113090,
        pcode: 'm25b',
        displayName: 'Europe Fantan',
        stream: 'https://loader2.idnstreams.com:6443/?app=Cam&name=FT_720P&volume=0.5',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['ball game'],
        url_game: '',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Shio Fight
    {
        name: 'Shio Fights',
        displayName: 'Shio Fights',
        periode: 2408611,
        pcode: 'm27',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=SF_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // 48D
    {
        name: '48D',
        displayName: '48D',
        periode: 955300,
        pcode: 'm35',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=48D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '48D B',
        displayName: 'Europe 48D',
        periode: 955300,
        pcode: 'm35b',
        stream: 'https://cam2.idnstreams.com/?app=HDMI&name=T14_720P',
        stream_hd: 'https://cam2.idnstreams.com/?app=HDMI&name=T14_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    // Domino
    {
        name: 'Domino',
        periode: 1164051,
        pcode: 'm41',
        displayName: 'Domino',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EDL_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=EDL_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['europe', 'original', 'card game'],
        url_game: 'new_domino_live_react/?pcode=m41',
        shoePeriode: '15146-114',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Domino B',
        displayName: 'Europe Domino',
        periode: 107,
        pcode: 'm41b',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T5_720P',
        stream_hd: 'https://eu.idnstreams.com/?app=HDMI&name=T5_1080P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '24Dspin',
        displayName: '24D Spin',
        periode: 2442812,
        pcode: 'm6',
        stream: 'https://cam2.idnstreams.com/?app=SDI&name=24DS_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '45691-201',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    // Ceme
    {
        name: 'Ceme',
        periode: 36382,
        pcode: 'm46',
        displayName: 'Europe Ceme',
        stream: 'https://loader2.idnstreams.com:6443/?app=Geo&name=CEME_720P&volume=0.5',
        stream_hd: 'https://loader2.idnstreams.com:6443/?app=Geo&name=CEME_1080P&volume=0.5',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        new_category: ['europe', 'original', 'card game'],
        url_game: 'new_ceme_react/?pcode=m46',
        shoePeriode: '203-32',
        order: 99,
        newSet: false,
        fast_table: true,
    },

    {
        name: '5D',
        displayName: '5D',
        periode: 1175738,
        pcode: 'm30',
        stream: 'https://cam4.idnstreams.com/?app=live&name=5D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'GongBall Jitu',
        displayName: 'Gong Ball Jitu',
        periode: 1423960,
        pcode: 'm33',
        stream: 'https://cam4.idnstreams.com/?app=live&name=GB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'others',
        shoePeriode: '35354-321',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Billiards',
        displayName: 'Billiards',
        periode: 1127130,
        pcode: 'm13',
        stream: 'https://cam4.idnstreams.com/?app=live&name=BL_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Gong Ball',
        displayName: 'Gong Ball',
        periode: 1423960,
        pcode: 'm16',
        stream: 'https://cam4.idnstreams.com/?app=live&name=GB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Niuniu',
        displayName: 'Niuniu',
        periode: 897991,
        pcode: 'm24',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=NN_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        shoePeriode: '54755-431',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'IDN 4 Stand',
        displayName: 'IDN 4 Stand',
        periode: 2533355,
        pcode: 'm28',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=IDN_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '41640-121',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Shio Balls',
        displayName: '3D Shio',
        periode: 843896,
        pcode: 'm29',
        stream: 'https://cam5.idnstreams.com/?app=live&name=3D_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '41640-121',
        order: 99,
        newSet: false,
        fast_table: false,
    },

    {
        name: 'Lotto',
        displayName: 'Race Ball',
        periode: 929980,
        pcode: 'm26',
        stream: 'https://cam3.idnstreams.com/?app=live&name=RC_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '46921-161',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Head Tail',
        displayName: 'Head Tail',
        periode: 3210724,
        pcode: 'm10',
        stream: 'https://cam3.idnstreams.com/?app=SDI&name=HNT_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Xoc Dia',
        displayName: 'Xoc Dia',
        periode: 1159776,
        pcode: 'm40',
        stream: 'https://cam4.idnstreams.com/?app=SDI&name=XD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Grand Prix',
        displayName: 'Grandprix Number',
        periode: 184006,
        pcode: 'm42',
        stream: 'https://cam3.idnstreams.com/?app=live&name=GP_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'balls',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: false,
    },
    {
        name: 'Duel Dice',
        displayName: 'Duel Dice',
        periode: 1002131,
        pcode: 'm39',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=DD_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Bingo Sicbo',
        displayName: 'Bingo Sicbo',
        periode: 2001533,
        pcode: 'm37',
        stream: 'https://cam3.idnstreams.com/?app=live&name=BS_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'dice',
        shoePeriode: '53760-351',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'IDN 4 Stand B',
        displayName: 'IDN 4 Stand B',
        periode: 2064086,
        pcode: 'm28b',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=IDNB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '0',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'other',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '3D',
        displayName: 'Sicbo Ball - Fast',
        periode: 2230843,
        pcode: 'm31',
        stream: 'https://cam3.idnstreams.com/?app=live&name=SB_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'ball',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'pasar',
        displayName: '6D Color',
        periode: 177084,
        pcode: 'm43',
        stream: 'https://cam5.idnstreams.com/?app=SDI&name=6D_720P',
        stream_hd: 'https://cam5.idnstreams.com/?app=SDI&name=6D_720P',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'balls',
        shoePeriode: '31428-51',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: '9-putts',
        periode: 108950,
        pcode: 'm45',
        displayName: '9-putts',
        stream: '',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['arcade'],
        url_game: 'arczone/9putts',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
    {
        name: 'Bounce Roulette',
        periode: 91790,
        pcode: 'p7f',
        displayName: 'Bounce Roulette',
        stream: 'https://eu.idnstreams.com/?app=HDMI&name=T9_720P',
        stream_hd: '',
        stream_uhd: '',
        stream_4k: '',
        stream_8k: '',
        bet: {},
        betHistory: [],
        newgame: '1',
        maintenance: '',
        maintenance_text: '',
        min: 1000,
        max: 1000000,
        min50: 5000,
        max50: 5000000,
        category: 'casino',
        new_category: ['arcade'],
        url_game: 'arczone/bounceroullete',
        shoePeriode: '',
        order: 99,
        newSet: false,
        fast_table: true,
    },
];
