import { PayoutData } from '../../../types';

export const payouts: Record<string, PayoutData[]> = {
    p6: [
        {
            name: 'one number',
            payout: 18,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'two numbers',
            payout: 8.5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'four numbers',
            payout: 3.75,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'single row',
            payout: 2.16,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'single column',
            payout: 3.75,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'double row',
            payout: 0.95,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'double column',
            payout: 1.37,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                {
                    name: 'big',
                    payout: 0.95,
                },
                {
                    name: 'small',
                    payout: 0.95,
                },
                {
                    name: 'odd',
                    payout: 0.95,
                },
                {
                    name: 'even',
                    payout: 0.95,
                },
                {
                    name: 'red',
                    payout: 0.95,
                },
                {
                    name: 'black',
                    payout: 0.95,
                },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
    p6b: [
        {
            name: 'one number',
            payout: 18,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'two numbers',
            payout: 8.5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'four numbers',
            payout: 3.75,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'single row',
            payout: 2.16,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'single column',
            payout: 3.75,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'double row',
            payout: 0.95,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'double column',
            payout: 1.375,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                {
                    name: 'big',
                    payout: 0.95,
                },
                {
                    name: 'small',
                    payout: 0.95,
                },
                {
                    name: 'odd',
                    payout: 0.95,
                },
                {
                    name: 'even',
                    payout: 0.95,
                },
                {
                    name: 'red',
                    payout: 0.95,
                },
                {
                    name: 'black',
                    payout: 0.95,
                },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
    p7d: [
        {
            name: 'single',
            payout: 35,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'split',
            payout: 17,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'street',
            payout: 11,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'corner',
            payout: 8,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'six line / double street',
            payout: 5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'trio',
            payout: 11,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'dozen',
            payout: 2,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'column',
            payout: 2,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                {
                    name: '1-18',
                    payout: 1,
                },
                {
                    name: '19-36',
                    payout: 1,
                },
                {
                    name: 'odd',
                    payout: 1,
                },
                {
                    name: 'even',
                    payout: 1,
                },
                {
                    name: 'red',
                    payout: 1,
                },
                {
                    name: 'black',
                    payout: 1,
                },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
    p7g: [
        {
            name: 'single',
            payout: 35,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'split',
            payout: 17,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'street',
            payout: 11,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'corner',
            payout: 8,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'six line / double street',
            payout: 5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'trio',
            payout: 11,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'dozen',
            payout: 2,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'column',
            payout: 2,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                {
                    name: '1-18',
                    payout: 1,
                },
                {
                    name: '19-36',
                    payout: 1,
                },
                {
                    name: 'odd',
                    payout: 1,
                },
                {
                    name: 'even',
                    payout: 1,
                },
                {
                    name: 'red',
                    payout: 1,
                },
                {
                    name: 'black',
                    payout: 1,
                },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
    p9b: [
        {
            name: 'jackpot',
            payout: 40,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'one number',
            payout: 9,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'two numbers',
            payout: 4,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'four numbers',
            payout: 1.5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'row bet',
            payout: 1.5,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'column bet',
            payout: 2.3,
            items: [],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                {
                    name: 'big',
                    payout: 0.95,
                },
                {
                    name: 'small',
                    payout: 0.95,
                },
                {
                    name: 'odd',
                    payout: 0.95,
                },
                {
                    name: 'even',
                    payout: 0.95,
                },
                {
                    name: 'red',
                    payout: 0.95,
                },
                {
                    name: 'black',
                    payout: 0.95,
                },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
    p12: [
        {
            name: 'single dice',
            payout: null,
            items: [
                { name: 'on one dice', payout: 1 },
                { name: 'on two dice', payout: 2 },
                { name: 'on three dice', payout: 3 },
            ],
            min: 1000,
            max: 1000000,
        },
        { name: 'dice combination', payout: 5, items: [], min: 1000, max: 1000000 },
        { name: 'specific double', payout: 10, items: [], min: 1000, max: 1000000 },
        { name: 'specific triple', payout: 180, items: [], min: 1000, max: 1000000 },
        { name: 'any triple', payout: 30, items: [], min: 1000, max: 1000000 },
        {
            name: 'sum three dice',
            payout: null,
            items: [
                { name: '4 or 17', payout: 50 },
                { name: '5 or 16', payout: 30 },
                { name: '6 or 15', payout: 18 },
                { name: '7 or 14', payout: 12 },
                { name: '8 or 13', payout: 8 },
                { name: '9 or 12', payout: 6 },
                { name: '10 or 11', payout: 6 },
            ],
            min: 1000,
            max: 1000000,
        },
        {
            name: 'side bet',
            payout: null,
            items: [
                { name: 'big', payout: 1 },
                { name: 'small', payout: 1 },
                { name: 'odd', payout: 1 },
                { name: 'even', payout: 1 },
            ],
            min: 5000,
            max: 5000000,
        },
    ],
};
